<div id="sidebar" class="sidebar                  responsive                    ace-save-state">
    <div class="sidebar-shortcuts" id="sidebar-shortcuts">
        <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
            <button class="btn btn-light">
                <a href="/dashboard">
                    <i class="ace-icon fa fa-tachometer"></i>
                </a>
            </button>

            <button class="btn btn-light">
                <a href="/customers">
                    <i class="ace-icon fa fa-users"></i>
                </a>

            </button>

            <button class="btn btn-light">
                <a href="/todos">
                    <i class="ace-icon fa fa-list"></i>
                </a>
            </button>

        </div>


    </div><!-- /.sidebar-shortcuts -->

    <ul class="nav nav-list">
        <li class="active">
            <a href="/dashboard">
                <i class="menu-icon fa fa-tachometer"></i>
                <span class="menu-text"> Dashboard </span>
            </a>

            <b class="arrow"></b>
        </li>

        <li class="">
            <a href="/customers" class="dropdown-toggle">
                <i class="menu-icon fa fa-users"></i>
                <span class="menu-text">
								Customers
							</span>
            </a>
        </li>

        <li class="">
            <a href="/todos" class="dropdown-toggle">
                <i class="menu-icon fa fa-list"></i>
                <span class="menu-text"> Todos </span>
            </a>
        </li>

    </ul><!-- /.nav-list -->
</div>