
<!DOCTYPE html>
<html lang="en"  ng-app="ContactApp" >
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8" />
    <title>Login Page - Customer Mangaer</title>

    <meta name="description" content="User login page" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <link rel="stylesheet" href="/app/assets/css/ace-skins.min.css" />
    <script src="/app/assets/js/ace-extra.min.js"></script>
    <link rel="stylesheet" href="/app/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/app/assets/css/bootstrap-colorpicker.min.css" />
    <link rel="stylesheet" href="/app/assets/css/bootstrap-datepicker3.min.css" />
    <link rel="stylesheet" href="/app/assets/css/bootstrap-duallistbox.min.css" />
    <link rel="stylesheet" href="/app/assets/css/bootstrap-editable.min.css" />
    <link rel="stylesheet" href="/app/assets/css/bootstrap-multiselect.min.css" />
    <link rel="stylesheet" href="/app/assets/css/bootstrap-timepicker.min.css" />
    <link rel="stylesheet" href="/app/assets/css/chosen.min.css" />
    <link rel="stylesheet" href="/app/assets/css/colorbox.min.css" />
    <link rel="stylesheet" href="/app/assets/css/daterangepicker.min.css" />
    <link rel="stylesheet" href="/app/assets/css/dropzone.min.css" />
    <link rel="stylesheet" href="/app/assets/css/font-awesome.min.css" />
    <link rel="stylesheet" href="/app/assets/css/fullcalendar.min.css" />
    <link rel="stylesheet" href="/app/assets/css/jquery.gritter.min.css" />
    <link rel="stylesheet" href="/app/assets/css/jquery-ui.custom.min.css" />
    <link rel="stylesheet" href="/app/assets/css/jquery-ui.min.css" />
    <link rel="stylesheet" href="/app/assets/css/prettify.min.css" />
    <link rel="stylesheet" href="/app/assets/css/select2.min.css" />
    <link rel="stylesheet" href="/app/assets/font-awesome/4.5.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="/app/assets/css/fonts.googleapis.com.css?family=Reenie+Beanie:regular" type="text/css"/>
    <link rel="stylesheet" href="/app/assets/css/ace.min.css" />
    <link rel="stylesheet" href="/app/assets/css/ace-part2.min.css"/>
    <link rel="stylesheet" href="/app/assets/css/ace-rtl.min.css" />
    <link rel="stylesheet" href="/app/assets/css/ace-ie.min.css"/>
    <script src="/app/assets/js/html5shiv.min.js"></script>
    <script src="/app/assets/js/respond.min.js"></script>
    <script src="/app/assets/js/jquery-1.11.3.min.js"></script>

    <script src="/app/bower_components/html5-boilerplate/dist/js/vendor/modernizr-2.8.3.min.js"></script>
    <script src="/app/assets/js/jquery-2.1.4.min.js"></script>
    <script src="/app/assets/js/ace.min.js"></script>

    <script src="/app/assets/js/ace-elements.min.js"></script>
    <script src="/app/assets/js/ace-extra.min.js"></script>
    <script src="/app/assets/js/autosize.min.js"></script>
    <script src="/app/assets/js/moment.min.js"></script>
    <script src="/app/assets/js/bootstrap.min.js"></script>
    <script src="/app/assets/js/bootstrap-colorpicker.min.js"></script>
    <script src="/app/assets/js/bootstrap-datepicker.min.js"></script>
    <script src="/app/assets/js/bootstrap-datetimepicker.min.js"></script>
    <script src="/app/assets/js/bootstrap-editable.min.js"></script>
    <script src="/app/assets/js/ace-editable.min.js"></script>
    <script src="/app/assets/js/bootstrap-markdown.min.js"></script>
    <script src="/app/assets/js/bootstrap-multiselect.min.js"></script>
    <script src="/app/assets/js/bootstrap-tag.min.js"></script>
    <script src="/app/assets/js/bootstrap-timepicker.min.js"></script>
    <script src="/app/assets/js/bootstrap-wysiwyg.min.js"></script>
    <script src="/app/assets/js/chosen.jquery.min.js"></script>
    <script src="/app/assets/js/daterangepicker.min.js"></script>
    <script src="/app/assets/js/dropzone.min.js"></script>
    <script src="/app/assets/js/excanvas.min.js"></script>

    <script src="/app/assets/js/fullcalendar.min.js"></script>
    <script src="/app/assets/js/grid.locale-en.js"></script>
    <script src="/app/assets/js/holder.min.js"></script>
    <script src="/app/assets/js/html5shiv.min.js"></script>
    <script src="/app/assets/js/jquery.bootstrap-duallistbox.min.js"></script>
    <script src="/app/assets/js/jquery.colorbox.min.js"></script>
    <script src="/app/assets/js/jquery.easypiechart.min.js"></script>
    <script src="/app/assets/js/jquery.flot.min.js"></script>
    <script src="/app/assets/js/jquery.flot.pie.min.js"></script>
    <script src="/app/assets/js/jquery.flot.resize.min.js"></script>
    <script src="/app/assets/js/jquery.hotkeys.index.min.js"></script>
    <script src="/app/assets/js/jquery.inputlimiter.min.js"></script>
    <script src="/app/assets/js/jquery.knob.min.js"></script>
    <script src="/app/assets/js/jquery.maskedinput.min.js"></script>
    <script src="/app/assets/js/jquery.mobile.custom.min.js"></script>
    <script src="/app/assets/js/jquery.nestable.min.js"></script>
    <script src="/app/assets/js/jquery.raty.min.js"></script>
    <script src="/app/assets/js/jquery.sparkline.index.min.js"></script>
    <script src="/app/assets/js/jquery.validate.min.js"></script>
    <script src="/app/assets/js/jquery-additional-methods.min.js"></script>
    <script src="/app/assets/js/jquery-ui.min.js"></script>
    <script src="/app/assets/js/bootbox.js"></script>
    <script src="/app/assets/js/markdown.min.js"></script>
    <script src="/app/assets/js/prettify.min.js"></script>
    <script src="/app/assets/js/respond.min.js"></script>
    <script src="/app/assets/js/select2.min.js"></script>
    <script src="/app/assets/js/spin.js"></script>
    <script src="/app/assets/js/tree.min.js"></script>
    <script src="/app/assets/js/wizard.min.js"></script>

  <!--  <script style="/app/js/angular-lib-min.js"></script>
    <script style="/app/js/components-min.js"></script>
    <script style="/app/js/app.js"></script>
    <script style=" /app/js/controller-libs-min.js"></script>-->
    <script src="/app/bower_components/angular/angular.js"></script>
    <script src="/app/bower_components/angular-route/angular-route.js"></script>
    <script src="/app/bower_components/angular-resource/angular-resource.js"></script>
    <script src="/app/bower_components/angular-moment/angular-moment.js"></script>
    <script src="/app/components/version/version.js"></script>
    <script src="/app/components/version/version-directive.js"></script>
    <script src="/app/components/version/interpolate-filter.js"></script>
    <script src="/app/bower_components/moment/min/moment-with-locales.js"></script>
    <script src="/app/bower_components/moment/moment.js"></script>
    <script src="/app/bower_components/moment/min/locales.min.js"></script>
    <script src="/app/js/app.js"></script>
    <script src="/app/js/Filters/filters.js"></script>
    <script src="/app/js/Components/modal.js"></script>
    <script src="/app/js/Services/Utils.js"></script>
    <script src="/app/js/Services/UserService.js"></script>
    <script src="/app/js/Services/CustomerService.js"></script>
    <script src="/app/js/Services/ConversationService.js"></script>
    <script src="/app/js/Services/MainService.js"></script>
    <script src="/app/js/Controllers/MainController.js"></script>
    <script src="/app/js/Controllers/UserController.js"></script>
    <script src="/app/js/Controllers/ConversationController.js"></script>
    <script src="/app/js/Controllers/NavController.js"></script>
    <script src="/app/js/Controllers/CustomerController.js"></script>
    <script src="/app/js/Controllers/DashboardController.js"></script>
    <base href="/">
    <script type="text/javascript">
        var __User = <?php echo json_encode(\Utils\Utility::setSession('user')); ?>;
    </script>
</head>

<body class="no-skin">
<span ng-controller="MainController as mainActions">
<modal ng-show="mainActions.show_modal" on-close-btn-clicked="mainActions.onCloseBtnClicked()" template="mainActions.modal_config.template" data=mainActions.modal_config.data buttons=mainActions.modal_config.buttons></modal>

    <span ng-include="'/app/templates/navbar.phtml'" ng-controller="navController as userDetails">

    </span>

    <div class="container-fluid">
              <div ng-init="mainActions.show_alert = false" ng-show="mainActions.show_alert" class="alert-bar alert dark  alert-dismissible {{mainActions.alert_config.type}}" role="alert">
                  <button type="button" class="close" ng-click="mainActions.onCloseBtnAlert()">
                    <span aria-hidden="true">×</span>
                  </button>
                  {{mainActions.alert_config.message}}
                </div>

        <script type="text/javascript">
    (function () {
        var s = document.createElement('script');
        s.async = true;
        s.onload = function () {
            EventSure.openTickets('4OT4NKB', {trigger:'#big_buy_button', ref:'qwertyuiop'});
        };
        s.src = "https://staging.eventsure.com.ng/js/widget.js";
        document.head.appendChild(s);
    })();

    </script>

        <div ng-view>

        </div>
    </div>
    <span ng-include="'/app/templates/footer.phtml'"></span>
</span>
</body>
</html>
